version: '3.8'
services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "80:80"
    networks:
      - supercaixa_network
    command: ["nginx", "-g", "daemon off;"]

  pdv1:
    build:
      context: ./pdv
      dockerfile: Dockerfile.pdv
    container_name: pdv1
    networks:
      - supercaixa_network
    environment:
      - DB_HOST=redis_db
    command: tail -f /dev/null

  pdv2:
    build:
      context: ./pdv
      dockerfile: Dockerfile.pdv
    container_name: pdv2
    networks:
      - supercaixa_network
    environment:
      - DB_HOST=redis_db
    command: tail -f /dev/null

  redis_db:
    build:
      context: ./db
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - supercaixa_network

networks:
  supercaixa_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
