# Dockerfile.pdv
FROM alpine:latest

# Instalar dependências
RUN apk add --no-cache redis dialog bash dos2unix bc openrc

# Criando pasta que irá conter os arquivos de configuração do PDV
RUN mkdir -p /etc/pdv/funcs

# Copiando os scripts PDV
COPY /scripts/pdv_interface.sh /bin/pdv
COPY /scripts/funcs/* /etc/pdv/funcs/

# Tornar os scripts executáveis
RUN chmod +x /bin/pdv
RUN chmod +x /etc/pdv/funcs/*

# Converter o script para formato Unix
RUN dos2unix /bin/pdv
RUN dos2unix /etc/pdv/funcs/*

