# Dockerfile para o servidor do SuperCaixa AI
FROM nginx:latest

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Expor a porta do serviço (ajuste conforme necessário)
EXPOSE 80

# Comando para rodar a aplicação
CMD ["tail -f /dev/null"]
