---
- name: Instalar e configurar Redis no db-sc01
  hosts: db-sc01
  become: yes
  tasks:
    - name: Atualizar os repositórios
      apk:
        update_cache: yes

    - name: Instalar Redis
      apk:
        name: redis
        state: present

    - name: Configurar Redis para aceitar conexões remotas
      lineinfile:
        path: /etc/redis.conf
        regexp: '^bind'
        line: 'bind 0.0.0.0'
      notify:
        - Reiniciar Redis

  handlers:
    - name: Reiniciar Redis
      service:
        name: redis
        state: restarted

    - name: Habilitar Redis no boot
      service:
        name: redis
        enabled: yes
